apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Hier trägt Azure DevOps später die Prod-Tags ein
images:
  - name: eduardgohl/budget-tracker-frontend
    newTag: "30"
  - name: eduardgohl/budget-tracker-backend
    newTag: "30"